### PR TITLE
Updated to ignore future UnityVS dll's - which are automatically

### PR DESCRIPTION
**Pull request by mikeyjk**
generated if missing. Updated to ignore auto generated txt. Textured
cube with good artwork.

### CODE REVIEW

**Comment by jstennant** [comment]
Your new material is in a directory called JeffTheCube/Materials/Materials. Probably unnecessary inception there :O

You seem to have deleted the Assemblies.meta file but not added it to the ignore list, so it'll just keep showing up in people's uncommitted changes.

**Comment by jstennant** [comment]
There also seem to be changes to the game scene, which we can't see in the diff (highlighting the problem you pointed out). I notice that the camera has been moved and that Jeff is now just called Cube. Difficult to see the reasoning at this point.

Also, the scene looks like this now:
capture
So I'm guessing there's a texture missing

And the wasd keys don't seem to do anything anymore.

Altogether, not my favorite changeset so far :'(

**Comment by mikeyjk** [comment]
fuc you this is the best changeset ever :neckbeard:

**Comment by jstennant** [comment]
My changeset was the pioneer amongst the plebeian changesets that followed. It was on shoulders like mine that this great dry-run was built.

mikey is the best

**Comment by mikeyjk** [comment]
doet @jstennant  :yellow_heart:

**Pull request closed without merging**
